---
- hosts: all
  tasks:
    - name: 'Instala pacotes do sistema operacional'
      apt: 
        name: 
        - php7.2
        - apache2
        - libapache2-mod-php7.2
        - php7.2-gd
        - php-ssh2 # libssh2-php
        - libssh2-1 # novo
        #- php5-mcrypt
        - mysql-server-5.7
        - python-mysqldb
        - php7.2-mysql
        - python-pymysql # NOVO- Pure-Python MySQL driver - Python 2.x
        - python3-pymysql # novo - Pure-Python MySQL Driver - Python 3.x
        state: latest
      become: yes
    - name: 'Cria o banco MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
#        login_password: 102030
        state: present
      become: yes
    - name: "Cria usuário do MySQL"
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 102030
        priv: 'wordpress_db.*:ALL'
        state: present