---
- hosts: all
  tasks:
    - name: 'Instala pacotes do sistema operacional'
      apt: 
        name: 
        - php7.2
        - apache2
        - libapache2-mod-php7.2
        - php7.2-gd
        - php-ssh2 # libssh2-php
        - libssh2-1 # novo
        #- php5-mcrypt
        - mysql-server-5.7
        - python-mysqldb
        - php7.2-mysql
        - python-pymysql # NOVO- Pure-Python MySQL driver - Python 2.x
        - python3-pymysql # novo - Pure-Python MySQL Driver - Python 3.x
        state: latest
      become: yes
    - name: 'Instala SQL'
      apt: 
        name: mysql-server
        state: present
      become: yes
    - name: Start SQL Service
      service:
        name: mysql
        state: started
      become: yes
      #here
    - name: create mysql database
      mysql_db:
        name: wordpress
        collation: utf8_general_ci
        encoding: utf8
        state: present
        login_host: '35.247.246.201' 
        login_password: "root"
        login_port: 3306
        login_user: "root"
        #  become: yes
#    - name: create user database
#      mysql_user:
#        name: wordpress_user
#        password: "root"
        #host: '%'
#        priv: "*.*:ALL"
#        login_user: "root"
#        login_password: "root"
        #login_port: "3306"
        #login_host: "35.247.246.201"
#        state: present
        
        #become: yes  
        #    - name: Cria usuario
        # mysql_user:
        # login_user: root
        #name: wordpress_user
        # password: 12345
        #priv: 'wordpress_db.*:ALL'
        #host: '%'
        #state: present
    - name: restart mysql
      service: 
        name: mysql
        state: restarted